steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/planar-airship-434723-g8/flask-app:$SHORT_SHA', '.']

  # Push Docker image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/planar-airship-434723-g8/flask-app:$SHORT_SHA']

  # Deploy to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/flask-app'
      - 'flask-app=gcr.io/planar-airship-434723-g8/flask-app:$SHORT_SHA'
      - '--namespace=default'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'

images:
  - 'gcr.io/planar-airship-434723-g8/flask-app:$SHORT_SHA'

substitutions:
  _ZONE: 'us-central1-a'
  _CLUSTER_NAME: 'my-cluster'

# Specify the logs bucket for Cloud Build
options:
  logsBucket: 'gs://my-cloud-build-logs'
