apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80  # External port
      targetPort: 6001  # Internal port
  type: LoadBalancer
